baseURL = "/"
title = "Spanish Cheatsheet"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowToc = true
TocOpen = true

[params.homeInfoParams]
Title = "Spanish Language Cheatsheet"
Content = "A comprehensive guide to Spanish language learning" 