baseURL = "/"
title = "Spanish Cheatsheet"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowToc = true
TocOpen = true

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 1

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true

[params.homeInfoParams]
Title = "Spanish Language Cheatsheet"
Content = "A comprehensive guide to Spanish language learning" 