baseURL = "https://example.com/"
title = "Spanish Grammar & Vocabulary Cheat Sheet"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Enable features
enableEmoji = true
enableRobotsTXT = true
enableSource = true
enableGitInfo = true

# Title handling and content settings
[params]
  env = "production"
  description = "A comprehensive reference guide for Spanish grammar and vocabulary"
  keywords = ["Spanish", "Grammar", "Vocabulary", "Cheat Sheet", "Reference"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  titleCaseStyle = "Go"
  # Header settings
  ShowToc = true
  TocOpen = true
  TocSide = "right"

[params.assets]
  disableHLJS = true
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "apple-touch-icon.png"

[params.header]
  enabled = true
  layout = "sticky"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[permalinks]
  post = "/:filename/"

[params.profileMode]
  enabled = false

[params.layout]
  mainSections = ["post"]
  listType = "default"
  [params.layout.list]
    [params.layout.list.simple]
      enable = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
